### ISSUE TITLE
Server crashed when use Mob Masher

### ISSUE THREAD

**Issue by cwc02777** [vadis365/Mob-Grinding-Utils#211] opened 2022-06-28 06:35 UTC
Minecraft 1.18.2
mob_grinding_utils-1.18.2-0.4.39
Forge 40.1.31

Server crashed  when  mob mashers run a few minute.

Error is "java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityType.m_20674_()" because "entitytype" is null"

at mob_grinding_utils.ModBlocks.lambda$static$34(ModBlocks.java:184) ~[mob_grinding_utils-1.18.2-0.4.39.jar%23234!/:1.18.2-0.4.39] {re:classloading}

Crash report
[crash-2022-06-28_13.56.53-server.txt](https://github.com/vadis365/Mob-Grinding-Utils/files/8998232/crash-2022-06-28_13.56.53-server.txt)

**Comment by Flanks255** [comment] 2022-06-28 21:03
Not actually related to the mob masher, its caused by Evilcraft blood stains sending a null somewhere its not supposed to be.
Fixed in 0.4.40

**Closed by Flanks255** 2022-06-28 21:03 UTC
