### ISSUE TITLE
Mob fan not recognising range upgrades (push distance)

### ISSUE THREAD

**Issue by stryker103** [vadis365/Mob-Grinding-Utils#104] opened 2018-10-01 10:48 UTC
Was going about setting up my normal mob farm (cursed earth + upgraded fan into mob masher) and went to test my 3x horizontal, 6x range upgrade fan. Horizontal upgrades had their effect but the range ones made no difference whether there be 6 or none. 
![image](https://user-images.githubusercontent.com/28218796/46284392-f7fde280-c5ba-11e8-89c2-39767440c917.png)
Without anything

![image](https://user-images.githubusercontent.com/28218796/46284403-04823b00-c5bb-11e8-8ef6-0188ee82511a.png)
With 3 range upgrades (showing the change)

![image](https://user-images.githubusercontent.com/28218796/46284417-0f3cd000-c5bb-11e8-8707-5217af7c246a.png)
With range upgrades (showing no change)

![image](https://user-images.githubusercontent.com/28218796/46284440-2bd90800-c5bb-11e8-8f10-ba4453e65dc8.png)
With it active showing no range effects. Standing to the side (in AoE) does push showing the side upgrades work

Version 0.3.11
Minecraft 1.12.2
Revelations
Tried relogging, breaking and replacing, trying single upgrades etc

**Comment by vadis365** [comment] 2018-10-26 14:29
hmmm... that is an unusual thing to happen. The fans are stopped by blocks placed in the line of block directly in front of them - make sure that is clear.

**Comment by stryker103** [comment] 2018-10-26 14:30
Is clear in front of them. Have used them with great success before hence my confusion. The only thing in front of them is me :P

**Comment by vadis365** [comment] 2018-10-26 14:33
Nothing has changed in the code recently other than adding the renderboxes - I'll take a look later on and see if I can replicate this.

**Comment by stryker103** [comment] 2018-10-26 14:34
Cheers
Ive swapped my farm to vector plates for now but would prefer to use the fans (due to being able to control them)

**Comment by stryker103** [comment] 2018-10-26 14:36
My last picture (standing to side) was badly worded. What i meant was that it pushes me that one block distance out to the sides (meaning the sideways range upgrades work) however adding the range (distance pushed) upgrades still only pushes me 1 block, just like standing in the middle

**Comment by stryker103** [comment] 2018-10-26 14:39
Interesting to note that is even the AOE indicator (blue area) doesnt change when adding the distance upgrades while the adding of the horizontal ones does change it. Might suggest its a code thing?

**Comment by vadis365** [comment] 2018-12-11 01:45
Hello,
I have tested this over and over and the fans work perfect for me. The only thing that can stop the fan from being at least 5 blocks range (without upgrades) is a block in front of them.
I really don't know what the issue is with your particular set up, but I honestly can't replicate the issue.
Sorry, but I'm closing this because it is a user specific issue,
Cheers,
Me.

**Closed by vadis365** 2018-12-11 01:45 UTC

**Comment by Psithief** [comment] 2020-03-26 12:21
I replicated this when activating the fan with a button in front of it. Unexpected behaviour, but the button can just be moved to an adjacent block to work around it.

**Comment by bommerhondjes14** [comment] 2021-06-03 15:37
I got the same issue today (1.16.5), I fixed it by placing blocks at the end of the range and breaking them again. After this it seemed to recognize the upgrade

**Comment by Flanks255** [comment] 2021-06-03 20:35
tested just now and they work fine.

**Comment by Corbi84** [comment] 2021-06-17 09:14
Created the account just to thank @bommerhondjes14 for his response! That bug was driving me nuts on ATM6 (1.6.10). 
Additionally the fan only showed a range of one block right in front of it when newly placed.

Just put a row of blocks in front of the fan and break them again and you can see the outline move with every block.

One a side note: The recipe for the Singularity Tank is missing, don't know whether that's pack- or code-specific. Plenty of other tanks in the pack, but you need a Singularity Tank in order to build the Drain Tank.

**Comment by Flanks255** [comment] 2021-07-18 15:18
the problem in 1.16.5 was fixed in commit 6117917
it was a problem with "cave air".

**Comment by Nendo-Bane** [comment] 2021-08-22 19:20
Having torches on the ground also prevent the upgrades from taking effect.

**Comment by Flanks255** [comment] 2021-08-23 00:36
I've been told that is on purpose, in case you get trapped in your own farm you can throw down anything and block it.

**Comment by Rabatata** [comment] 2023-06-08 21:51
The bug is apparently fixed though, for those who might be looking. (Which was my case) My problem was a torch in front of the fan!
