### ISSUE TITLE
Ticking Block Entity - Server Crash

### ISSUE THREAD

**Issue by DarkDon** [vadis365/Mob-Grinding-Utils#127] opened 2019-07-05 20:23 UTC
Which Pack am i using:

Project Ozone 3 - 3.0.41

Problem:

Server crashes - Crash report -> Ticking Block entity

Crash Report

-- Head --
Thread: Server thread
Stacktrace:
	at twilightforest.util.TFItemStackUtils.consumeInventoryItem(TFItemStackUtils.java:19)
	at twilightforest.TFEventListener.charmOfLife(TFEventListener.java:253)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_152_TFEventListener_charmOfLife_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:614)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1168)
	at p455w0rd.endermanevo.entity.EntityEvolvedEnderman.func_70097_a(EntityEvolvedEnderman.java:308)
	at mob_grinding_utils.items.ItemImaginaryInvisibleNotReallyThereSword.func_77644_a(ItemImaginaryInvisibleNotReallyThereSword.java:25)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:366)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1421)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425)
	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:99)
	at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:63)

-- Block entity being ticked --
Details:
	Name: minecraft:tile.mob_grinding_utils.saw // mob_grinding_utils.tile.TileEntitySaw
	Block type: ID #3822 (tile.mob_grinding_utils.saw // mob_grinding_utils.blocks.BlockSaw // mob_grinding_utils:saw)
	Block data value: 10 / 0xA / 0b1010
	Block location: World: (-1219,84,-42), Chunk: (at 13,5,6 in -77,-3; contains blocks -1232,0,-48 to -1217,255,-33), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Actual block type: ID #3822 (tile.mob_grinding_utils.saw // mob_grinding_utils.blocks.BlockSaw // mob_grinding_utils:saw)
	Actual block data value: 10 / 0xA / 0b1010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: World2
	All players: 1 total; [GCEntityPlayerMP['DonKun234'/404, l='World2', x=-1206.66, y=84.00, z=3.18]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: -6721530720900451440
	Level generator: ID 06 - botania-skyblock, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1208,86,-4), Chunk: (at 8,5,12 in -76,-1; contains blocks -1216,0,-16 to -1201,255,-1), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 867220 game time, 876440 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 110995 (now: false), thunder time: 58627 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

Maybe you can enlight me how to fix this even if its not your mod causing this, pls tell me which mod i need to fix and i find a way ^^

thx in regards

**Comment by WickedxALex** [comment] 2019-07-07 18:33
omg im having this same problem with the excate same error and same mod pack it seems to be even more of a problem when i use a Drop of Evil

**Comment by Barodas** [comment] 2019-07-14 02:25
I've had the same issue. It appears to be caused by Evolved Enderman from the Enderman Evolution mod interacting with spikes as they're killed. Crash will occur with spikes from this mod or Extra Utilities 2. 

The quick solution is to remove Enderman Evolution. Make sure you backup your world first just in case.

**Comment by WickedxAlex** [comment] 2019-07-14 21:22
weird as i wasnt using spikes but took the mod out and now everything seems to be fine for me :) hopefully same thing works for DarkDon so thanks Barodas

**Comment by nightstick24** [comment] 2019-08-03 01:15
Same issue here. https://pastebin.com/cDr3hPJC

Removing the Evolved Enderman entity with MCEdit fixes the issue if you can't get into your world.

**Comment by vadis365** [comment] 2019-11-23 17:06
closing then.

**Closed by vadis365** 2019-11-23 17:06 UTC
